'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmregistrofuncionarios

    '''<summary>
    '''lblidentificacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblidentificacion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtidentificacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtidentificacion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblnombre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblnombre As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtnombre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtnombre As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblprimerapellido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblprimerapellido As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtprimerapellido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtprimerapellido As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblsegundoapellido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblsegundoapellido As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtsegundoapellido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtsegundoapellido As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblestado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblestado As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Activo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Activo As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblactivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblactivo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Inactivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Inactivo As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblinactivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblinactivo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btregistrar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btregistrar As Global.System.Web.UI.WebControls.Button
End Class
