'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmregistro_de_productos

    '''<summary>
    '''lblnombreproducto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblnombreproducto As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtnombreproducto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtnombreproducto As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblcodigoproducto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcodigoproducto As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtcodigoproducto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcodigoproducto As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblcantidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcantidad As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtcantidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcantidad As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btregistrarP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btregistrarP As Global.System.Web.UI.WebControls.Button
End Class
